"""
maskme.analytics.risk.report
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HTML report generator for re-identification risk analytics.

This module is fully agnostic to specific risk metrics — it works exclusively
with RiskResult objects. Adding a new risk metric never requires changes
here.

Public API:
    generate(results, output_path, dataset_info)
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from maskme.analytics.risk.metrics.base import RiskResult


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate(
    results: List[RiskResult],
    output_path: str,
    dataset_info: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Generate a self-contained HTML risk report and write it to disk.

    Iterates over RiskResult objects — no knowledge of k-anonymity,
    l-diversity, or any specific risk metric is required.

    Args:
        results:      List of computed RiskResult instances.
                      Charts must already be populated (result.charts).
        output_path:  Destination path for the HTML file.
        dataset_info: Optional metadata to display in the header section
                      (e.g. {"records": 5000, "source": "patients.csv"}).
    """
    doc = _build_document(results, dataset_info or {})
    Path(output_path).write_text(doc, encoding="utf-8")


# ---------------------------------------------------------------------------
# Document assembly
# ---------------------------------------------------------------------------

def _build_document(
    results: List[RiskResult],
    dataset_info: Dict[str, Any],
) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    overall_pass = all(r.passed for r in results)
    verdict_cls  = "verdict-pass" if overall_pass else "verdict-fail"
    verdict_txt  = "PASSED" if overall_pass else "FAILED"

    nav_links = "\n".join(
        f'<a href="#{_slug(r.name)}">{_esc(r.name)}</a>'
        for r in results
    )

    sections = "\n".join(_section(r) for r in results)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>MaskMe — Re-identification Risk Report</title>
  <style>{_CSS}</style>
</head>
<body>

<header class="site-header">
  <div class="header-inner">
    <div class="header-brand">
      <span class="logo">🔒</span>
      <div>
        <h1>Re-identification Risk Report</h1>
        <p class="subtitle">Generated by MaskMe · {generated_at}</p>
      </div>
    </div>
    <span class="badge {verdict_cls}">{verdict_txt}</span>
  </div>
</header>

<nav class="toc">
  <span class="toc-label">Jump to:</span>
  <a href="#summary">Summary</a>
  {nav_links}
  <a href="#recommendations">Recommendations</a>
</nav>

<main>

{_summary_section(results, dataset_info, overall_pass)}

{sections}

{_recommendations_section(results)}

</main>

<footer>
  <p>MaskMe · Re-identification Risk Report · {generated_at}</p>
  <p class="footer-refs">
    References: Samarati &amp; Sweeney (1998) · Machanavajjhala et al. (2007)
    · Li, Li &amp; Venkatasubramanian (2007)
  </p>
</footer>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Executive summary
# ---------------------------------------------------------------------------

def _summary_section(
    results: List[RiskResult],
    dataset_info: Dict[str, Any],
    overall_pass: bool,
) -> str:
    verdict_cls = "verdict-pass" if overall_pass else "verdict-fail"
    verdict_msg = (
        "All risk metrics passed. The dataset meets the configured "
        "re-identification risk thresholds."
        if overall_pass else
        "One or more risk metrics failed. Review the sections below and "
        "apply the recommended mitigations before publishing this dataset."
    )

    # Dataset info cards
    info_cards = ""
    if dataset_info:
        for key, val in dataset_info.items():
            info_cards += (
                f'<div class="info-card">'
                f'<span class="info-val">{_esc(str(val))}</span>'
                f'<span class="info-key">{_esc(str(key))}</span>'
                f'</div>'
            )

    # Analytic verdict pills
    pills = ""
    for r in results:
        cls  = "pill-pass" if r.passed else "pill-fail"
        icon = "✓" if r.passed else "✗"
        pills += (
            f'<a href="#{_slug(r.name)}" class="pill {cls}">'
            f'{icon} {_esc(r.name)}</a>'
        )

    return f"""
<section id="summary" class="card">
  <h2>Executive Summary</h2>
  <div class="verdict-banner {verdict_cls}">
    <span class="verdict-icon">{"✓" if overall_pass else "✗"}</span>
    <span>{verdict_msg}</span>
  </div>
  {"<div class='info-grid'>" + info_cards + "</div>" if info_cards else ""}
  <div class="pills">{pills}</div>
</section>"""


# ---------------------------------------------------------------------------
# Per-analytic section
# ---------------------------------------------------------------------------

def _section(result: RiskResult) -> str:
    passed_cls = "badge-pass" if result.passed else "badge-fail"
    passed_txt = "PASSED" if result.passed else "FAILED"

    # Summary metrics table
    metrics_rows = "\n".join(
        f"<tr><td>{_esc(str(k))}</td><td><strong>{_esc(str(v))}</strong></td></tr>"
        for k, v in result.summary.items()
        if k not in ("size_distribution", "diversity_distribution",
                     "emd_values", "passed")
    )

    # Charts
    charts_html = ""
    for svg in result.charts:
        charts_html += f'<div class="chart-wrap">{svg}</div>'

    # Details table (first 50 rows max for readability)
    details_html = _details_table(result.details[:50])
    truncation   = (
        f'<p class="note">Showing first 50 of {len(result.details)} '
        f'equivalence classes.</p>'
        if len(result.details) > 50 else ""
    )

    # Metadata
    meta_items = " · ".join(
        f"<strong>{_esc(str(k))}:</strong> {_esc(str(v))}"
        for k, v in result.metadata.items()
    )

    return f"""
<section id="{_slug(result.name)}" class="card">
  <div class="section-header">
    <h2>{_esc(result.name)}</h2>
    <span class="badge {passed_cls}">{passed_txt}</span>
  </div>

  {"<p class='meta'>" + meta_items + "</p>" if meta_items else ""}

  <div class="two-col">
    <div>
      <h3>Metrics</h3>
      <table class="metrics-table">
        <tbody>{metrics_rows}</tbody>
      </table>
    </div>
    <div class="charts">
      {charts_html if charts_html else '<p class="note">No chart available.</p>'}
    </div>
  </div>

  <h3>Equivalence Class Details</h3>
  {truncation}
  {details_html}
</section>"""


def _details_table(details: List[Dict[str, Any]]) -> str:
    if not details:
        return '<p class="note">No details available.</p>'

    headers = list(details[0].keys())
    thead   = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    rows    = ""
    for row in details:
        cells = ""
        for h in headers:
            val   = row.get(h, "")
            cls   = ""
            if h == "satisfies_k" or h == "satisfies_l" or h == "satisfies_t":
                cls = "cell-pass" if val else "cell-fail"
                val = "✓" if val else "✗"
            elif h == "risk":
                level = float(val) if val else 0
                cls   = "cell-fail" if level > 0.5 else (
                    "cell-warn" if level > 0.2 else "cell-pass"
                )
            cells += f'<td class="{cls}">{_esc(str(val))}</td>'
        rows += f"<tr>{cells}</tr>"

    return f"""
<div class="table-wrap">
  <table class="details-table">
    <thead><tr>{thead}</tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>"""


# ---------------------------------------------------------------------------
# Consolidated recommendations
# ---------------------------------------------------------------------------

def _recommendations_section(results: List[RiskResult]) -> str:
    items = ""
    for result in results:
        if not result.recommendations:
            continue
        passed_cls = "rec-pass" if result.passed else "rec-fail"
        items     += f'<h3 class="{passed_cls}">{_esc(result.name)}</h3><ol>'
        for rec in result.recommendations:
            items += f"<li>{_esc(rec)}</li>"
        items += "</ol>"

    return f"""
<section id="recommendations" class="card">
  <h2>Recommendations</h2>
  {items if items else '<p class="note">No recommendations.</p>'}
</section>"""


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _slug(name: str) -> str:
    """Convert an analytic name to a URL-safe HTML id."""
    return name.lower().replace(" ", "-").replace("_", "-")


def _esc(value: str) -> str:
    """Escape HTML special characters."""
    return html.escape(str(value))


# ---------------------------------------------------------------------------
# Embedded CSS
# ---------------------------------------------------------------------------

_CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  font-size: 14px;
  line-height: 1.6;
  color: #1F2937;
  background: #F3F4F6;
}

/* Header */
.site-header {
  background: #1F2937;
  color: #fff;
  padding: 20px 32px;
}
.header-inner {
  max-width: 1100px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}
.header-brand { display: flex; align-items: center; gap: 14px; }
.logo { font-size: 28px; }
.site-header h1 { font-size: 20px; font-weight: 600; }
.subtitle { font-size: 12px; color: #9CA3AF; margin-top: 2px; }

/* Nav */
.toc {
  background: #fff;
  border-bottom: 1px solid #E5E7EB;
  padding: 10px 32px;
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  font-size: 13px;
  position: sticky;
  top: 0;
  z-index: 10;
}
.toc-label { color: #6B7280; font-weight: 500; }
.toc a { color: #3B82F6; text-decoration: none; }
.toc a:hover { text-decoration: underline; }

/* Main */
main {
  max-width: 1100px;
  margin: 24px auto;
  padding: 0 24px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Cards */
.card {
  background: #fff;
  border-radius: 10px;
  padding: 24px 28px;
  box-shadow: 0 1px 3px rgba(0,0,0,.08);
}
.card h2 {
  font-size: 17px;
  font-weight: 600;
  margin-bottom: 16px;
  color: #111827;
}
.card h3 {
  font-size: 14px;
  font-weight: 600;
  color: #374151;
  margin: 16px 0 8px;
}

/* Badges */
.badge {
  display: inline-block;
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: .04em;
}
.badge-pass, .verdict-pass { background: #D1FAE5; color: #065F46; }
.badge-fail, .verdict-fail { background: #FEE2E2; color: #991B1B; }

/* Verdict banner */
.verdict-banner {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 14px 18px;
  border-radius: 8px;
  font-size: 13px;
  margin-bottom: 16px;
}
.verdict-icon { font-size: 18px; line-height: 1; flex-shrink: 0; }

/* Info grid */
.info-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 16px;
}
.info-card {
  background: #F9FAFB;
  border: 1px solid #E5E7EB;
  border-radius: 8px;
  padding: 10px 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  min-width: 100px;
}
.info-val { font-size: 20px; font-weight: 700; color: #1F2937; }
.info-key { font-size: 11px; color: #6B7280; margin-top: 2px; }

/* Pills */
.pills { display: flex; flex-wrap: wrap; gap: 8px; }
.pill {
  display: inline-block;
  padding: 5px 14px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 600;
  text-decoration: none;
}
.pill-pass { background: #D1FAE5; color: #065F46; }
.pill-fail { background: #FEE2E2; color: #991B1B; }

/* Section header */
.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}

/* Meta */
.meta { font-size: 11px; color: #6B7280; margin-bottom: 14px; }

/* Two-column layout */
.two-col {
  display: grid;
  grid-template-columns: 280px 1fr;
  gap: 24px;
  align-items: start;
  margin-top: 12px;
}
@media (max-width: 750px) {
  .two-col { grid-template-columns: 1fr; }
}

/* Metrics table */
.metrics-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.metrics-table td {
  padding: 6px 8px;
  border-bottom: 1px solid #F3F4F6;
}
.metrics-table td:first-child { color: #6B7280; }

/* Charts */
.charts { display: flex; flex-direction: column; gap: 16px; }
.chart-wrap svg { width: 100%; height: auto; border-radius: 8px; }

/* Details table */
.table-wrap {
  overflow-x: auto;
  margin-top: 8px;
  border-radius: 8px;
  border: 1px solid #E5E7EB;
}
.details-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.details-table th {
  background: #F9FAFB;
  padding: 8px 12px;
  text-align: left;
  font-weight: 600;
  color: #374151;
  border-bottom: 1px solid #E5E7EB;
  white-space: nowrap;
}
.details-table td {
  padding: 7px 12px;
  border-bottom: 1px solid #F3F4F6;
  color: #374151;
}
.details-table tr:last-child td { border-bottom: none; }
.details-table tr:hover td { background: #F9FAFB; }
.cell-pass { color: #065F46; font-weight: 600; }
.cell-fail { color: #991B1B; font-weight: 600; }
.cell-warn { color: #92400E; font-weight: 600; }

/* Recommendations */
.rec-pass { color: #065F46; }
.rec-fail { color: #991B1B; }
#recommendations ol {
  padding-left: 20px;
  margin-bottom: 16px;
}
#recommendations li {
  margin-bottom: 6px;
  font-size: 13px;
  color: #374151;
}

/* Footer */
footer {
  text-align: center;
  padding: 24px;
  color: #9CA3AF;
  font-size: 12px;
}
.footer-refs { margin-top: 4px; font-style: italic; }

/* Utility */
.note { font-size: 12px; color: #6B7280; font-style: italic; margin: 6px 0; }
"""