"""
maskme.utility.report
~~~~~~~~~~~~~~~~~~~~~~
HTML report generator for data utility metrics.

Fully agnostic to specific metrics — works exclusively with
UtilityResult objects. Adding a new metric never requires changes here.

Public API:
    generate(results, output_path, dataset_info)
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from maskme.analytics.utility.metrics.base import UtilityResult


def generate(
    results: List[UtilityResult],
    output_path: str,
    dataset_info: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Generate a self-contained HTML utility report and write it to disk.

    Args:
        results:      List of computed UtilityResult instances with charts.
        output_path:  Destination path for the HTML file.
        dataset_info: Optional metadata for the header section.
    """
    doc = _build_document(results, dataset_info or {})
    Path(output_path).write_text(doc, encoding="utf-8")


def _build_document(results, dataset_info):
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    overall_pass = all(r.passed for r in results)
    avg_score    = round(sum(r.score for r in results) / len(results), 3) \
                   if results else 0.0
    verdict_cls  = "verdict-pass" if overall_pass else "verdict-fail"
    verdict_txt  = "ACCEPTABLE" if overall_pass else "REVIEW NEEDED"

    nav_links = "\n".join(
        f'<a href="#{_slug(r.name)}">{_esc(r.name)}</a>' for r in results
    )
    sections = "\n".join(_section(r) for r in results)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>MaskMe — Data Utility Report</title>
  <style>{_CSS}</style>
</head>
<body>
<header class="site-header">
  <div class="header-inner">
    <div class="header-brand">
      <div>
        <h1>Data Utility Report</h1>
        <p class="subtitle">Generated by MaskMe · {generated_at}</p>
      </div>
    </div>
    <div class="header-right">
      <div class="score-badge">
        <span class="score-val">{avg_score:.0%}</span>
        <span class="score-lbl">Avg utility</span>
      </div>
      <span class="badge {verdict_cls}">{verdict_txt}</span>
    </div>
  </div>
</header>
<nav class="toc">
  <span class="toc-label">Jump to:</span>
  <a href="#summary">Summary</a>
  {nav_links}
  <a href="#recommendations">Recommendations</a>
</nav>
<main>
{_summary_section(results, dataset_info, overall_pass, avg_score)}
{sections}
{_recommendations_section(results)}
</main>
<footer>
  <p>MaskMe · Data Utility Report · {generated_at}</p>
  <p class="footer-note">Utility score = 1 − ILI. Score of 1.0 = data statistically identical to original.</p>
</footer>
</body>
</html>"""


def _summary_section(results, dataset_info, overall_pass, avg_score):
    verdict_cls = "verdict-pass" if overall_pass else "verdict-fail"
    verdict_msg = (
        f"Average utility score is {avg_score:.0%}. All metrics pass — "
        "the anonymised dataset retains sufficient analytical utility."
        if overall_pass else
        f"Average utility score is {avg_score:.0%}. One or more metrics fall "
        "below threshold. Review recommendations before using this dataset."
    )
    info_cards = "".join(
        f'<div class="info-card"><span class="info-val">{_esc(str(v))}</span>'
        f'<span class="info-key">{_esc(str(k))}</span></div>'
        for k, v in dataset_info.items()
    )
    pills = "".join(
        f'<a href="#{_slug(r.name)}" class="pill-score '
        f'{"pill-pass" if r.passed else "pill-fail"}">'
        f'{_esc(r.name)}: {r.score:.0%}</a>'
        for r in results
    )
    return f"""
<section id="summary" class="card">
  <h2>Executive Summary</h2>
  <div class="verdict-banner {verdict_cls}">
    <span class="verdict-icon">{"✓" if overall_pass else "⚠"}</span>
    <span>{verdict_msg}</span>
  </div>
  {"<div class='info-grid'>" + info_cards + "</div>" if info_cards else ""}
  <div class="pills">{pills}</div>
</section>"""


def _section(result: UtilityResult) -> str:
    score_cls  = ("score-high" if result.score >= 0.8 else
                  "score-medium" if result.score >= 0.5 else "score-low")
    passed_cls = "badge-pass" if result.passed else "badge-fail"
    passed_txt = "PASSED" if result.passed else "FAILED"

    skip_keys = {"per_field", "fields", "numerical_fields", "categorical_fields",
                 "high_loss_fields", "low_loss_fields", "low_fidelity_fields", "passed"}
    metrics_rows = "\n".join(
        f"<tr><td>{_esc(str(k))}</td><td><strong>{_esc(str(v))}</strong></td></tr>"
        for k, v in result.summary.items() if k not in skip_keys
    )
    charts_html = "".join(f'<div class="chart-wrap">{svg}</div>'
                          for svg in result.charts) \
                  or '<p class="note">No chart available.</p>'
    details_html = _details_table(result.details[:50])
    truncation   = (
        f'<p class="note">Showing first 50 of {len(result.details)} fields.</p>'
        if len(result.details) > 50 else ""
    )
    meta_items = " · ".join(
        f"<strong>{_esc(str(k))}:</strong> {_esc(str(v))}"
        for k, v in result.metadata.items()
        if k not in ("ili_formula",)
    )

    return f"""
<section id="{_slug(result.name)}" class="card">
  <div class="section-header">
    <h2>{_esc(result.name)}</h2>
    <div class="section-badges">
      <span class="score-pill {score_cls}">{result.score:.0%}</span>
      <span class="badge {passed_cls}">{passed_txt}</span>
    </div>
  </div>
  {"<p class='meta'>" + meta_items + "</p>" if meta_items else ""}
  <p class="threshold-note">Threshold: {result.threshold:.0%} · Score: <span class="{score_cls}">{result.score:.0%}</span></p>
  <div class="two-col">
    <div>
      <h3>Metrics</h3>
      <table class="metrics-table"><tbody>{metrics_rows}</tbody></table>
    </div>
    <div class="charts">{charts_html}</div>
  </div>
  <h3>Field-level Details</h3>
  {truncation}{details_html}
</section>"""


def _details_table(details):
    if not details:
        return '<p class="note">No details available.</p>'
    headers = list(details[0].keys())
    thead   = "".join(f"<th>{_esc(h)}</th>" for h in headers)
    rows    = ""
    for row in details:
        cells = ""
        for h in headers:
            val = row.get(h, "")
            cls = ""
            if h == "loss_level":
                cls = {"low":"cell-pass","moderate":"cell-warn","high":"cell-fail"}.get(str(val),"")
            elif h == "status":
                cls = {"unchanged":"cell-pass","partial":"cell-warn","dropped":"cell-fail"}.get(str(val),"")
            elif h in ("fidelity", "retention_rate"):
                try:
                    f   = float(val)
                    cls = "cell-pass" if f >= 0.8 else ("cell-warn" if f >= 0.5 else "cell-fail")
                except (ValueError, TypeError):
                    pass
            elif h == "ili":
                try:
                    f   = float(val)
                    cls = "cell-fail" if f > 0.5 else ("cell-warn" if f > 0.2 else "cell-pass")
                    val = f"{f:.1%}"
                except (ValueError, TypeError):
                    pass
            cells += f'<td class="{cls}">{_esc(str(val))}</td>'
        rows += f"<tr>{cells}</tr>"
    return f"""
<div class="table-wrap">
  <table class="details-table">
    <thead><tr>{thead}</tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>"""


def _recommendations_section(results):
    items = ""
    for result in results:
        if not result.recommendations:
            continue
        cls    = "rec-pass" if result.passed else "rec-fail"
        items += f'<h3 class="{cls}">{_esc(result.name)}</h3><ol>'
        for rec in result.recommendations:
            items += f"<li>{_esc(rec)}</li>"
        items += "</ol>"
    return f"""
<section id="recommendations" class="card">
  <h2>Recommendations</h2>
  {items or '<p class="note">No recommendations.</p>'}
</section>"""


def _slug(name): return name.lower().replace(" ","-").replace("_","-")
def _esc(value): return html.escape(str(value))


_CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  font-size: 14px;
  line-height: 1.6;
  color: #2E2E2E;
  background: #FFFDD0;
}

/* Header */
.site-header {
  background: #556B2F;
  color: #fff;
  padding: 20px 32px;
}
.header-inner {
  max-width: 1100px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}
.header-right { display: flex; align-items: center; gap: 12px; }
.header-brand { display: flex; align-items: center; gap: 14px; }
.site-header h1 { font-size: 20px; font-weight: 600; }
.subtitle { font-size: 12px; color: #C5C5A0; margin-top: 2px; }

/* Score badge in header */
.score-badge {
  display: flex;
  flex-direction: column;
  align-items: center;
  background: rgba(255,255,255,.12);
  border-radius: 8px;
  padding: 6px 14px;
}
.score-val { font-size: 22px; font-weight: 700; }
.score-lbl { font-size: 10px; color: #C5C5A0; }

/* Nav */
.toc {
  background: #fff;
  border-bottom: 1px solid #E8E4C8;
  padding: 10px 32px;
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  font-size: 13px;
  position: sticky;
  top: 0;
  z-index: 10;
}
.toc-label { color: #8B8B7A; font-weight: 500; }
.toc a { color: #556B2F; text-decoration: none; }
.toc a:hover { text-decoration: underline; }

/* Main */
main {
  max-width: 1100px;
  margin: 24px auto;
  padding: 0 24px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Cards */
.card {
  background: #fff;
  border-radius: 10px;
  padding: 24px 28px;
  box-shadow: 0 1px 3px rgba(0,0,0,.08);
}
.card h2 {
  font-size: 17px;
  font-weight: 600;
  margin-bottom: 16px;
  color: #556B2F;
}
.card h3 {
  font-size: 14px;
  font-weight: 600;
  color: #4A4A4A;
  margin: 16px 0 8px;
}

/* Badges */
.badge {
  display: inline-block;
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: .04em;
}
.badge-pass { background: #E8F0D5; color: #3D6B1E; }
.badge-fail { background: #F5DDD9; color: #A03A2A; }

/* Verdict banners */
.verdict-pass { background: #ECF4E0; color: #3D6B1E; }
.verdict-fail { background: #F8E4E0; color: #A03A2A; }
.verdict-banner {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 14px 18px;
  border-radius: 8px;
  font-size: 13px;
  margin-bottom: 16px;
}
.verdict-icon { font-size: 18px; line-height: 1; flex-shrink: 0; }

/* Info grid */
.info-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 16px;
}
.info-card {
  background: #F5F3E8;
  border: 1px solid #E8E4C8;
  border-radius: 8px;
  padding: 10px 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  min-width: 100px;
}
.info-val { font-size: 20px; font-weight: 700; color: #2E2E2E; }
.info-key { font-size: 11px; color: #8B8B7A; margin-top: 2px; }

/* Pills */
.pills { display: flex; flex-wrap: wrap; gap: 8px; }
.pill-score {
  display: inline-block;
  padding: 5px 14px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 600;
  text-decoration: none;
}
.pill-pass { background: #E8F0D5; color: #3D6B1E; }
.pill-fail { background: #F5DDD9; color: #A03A2A; }

/* Section header */
.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}
.section-badges { display: flex; align-items: center; gap: 8px; }

/* Score pills inside sections */
.score-pill {
  display: inline-block;
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 13px;
  font-weight: 700;
}
.score-high { background: #E8F0D5; color: #3D6B1E; }
.score-medium { background: #F5ECD0; color: #A67A20; }
.score-low { background: #F5DDD9; color: #A03A2A; }

/* Meta */
.meta { font-size: 11px; color: #8B8B7A; margin-bottom: 8px; }
.threshold-note { font-size: 12px; color: #8B8B7A; margin-bottom: 14px; }

/* Two-column layout */
.two-col {
  display: grid;
  grid-template-columns: 280px 1fr;
  gap: 24px;
  align-items: start;
  margin-top: 12px;
}
@media (max-width: 750px) {
  .two-col { grid-template-columns: 1fr; }
}

/* Metrics table */
.metrics-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.metrics-table td {
  padding: 6px 8px;
  border-bottom: 1px solid #E8E4C8;
}
.metrics-table td:first-child { color: #8B8B7A; }

/* Charts */
.charts { display: flex; flex-direction: column; gap: 16px; }
.chart-wrap svg { width: 100%; height: auto; border-radius: 8px; }

/* Details table */
.table-wrap {
  overflow-x: auto;
  margin-top: 8px;
  border-radius: 8px;
  border: 1px solid #E8E4C8;
}
.details-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}
.details-table th {
  background: #F5F3E8;
  padding: 8px 12px;
  text-align: left;
  font-weight: 600;
  color: #4A4A4A;
  border-bottom: 1px solid #E8E4C8;
  white-space: nowrap;
}
.details-table td {
  padding: 7px 12px;
  border-bottom: 1px solid #E8E4C8;
  color: #4A4A4A;
}
.details-table tr:last-child td { border-bottom: none; }
.details-table tr:hover td { background: #F5F3E8; }
.cell-pass { color: #3D6B1E; font-weight: 600; }
.cell-fail { color: #A03A2A; font-weight: 600; }
.cell-warn { color: #A67A20; font-weight: 600; }

/* Recommendations */
.rec-pass { color: #3D6B1E; margin-top: 16px; }
.rec-fail { color: #A03A2A; margin-top: 16px; }
#recommendations ol { padding-left: 20px; margin-bottom: 12px; }
#recommendations li { margin-bottom: 6px; font-size: 13px; color: #4A4A4A; }

/* Footer */
footer {
  text-align: center;
  padding: 24px;
  color: #8B8B7A;
  font-size: 12px;
}
.footer-note { margin-top: 4px; font-style: italic; }

/* Utility */
.note { font-size: 12px; color: #8B8B7A; font-style: italic; margin: 6px 0; }
"""