site_name: MaskMe Documentation
site_description: Professional framework for data anonymization and risk analysis.

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Architecture: engine.md
  - Strategies:
      - Overview: strategies/reference.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js