"""
maskme.analytics.risk.base
~~~~~~~~~~~~~~~~~~~~~~
Formal contracts for the re-identification risk layer.

Two building blocks:

    RiskResult — a standardised dataclass that every risk metric returns.
                     report.py and visual.py work exclusively with this
                     type, making them agnostic to any specific metric.

    Metric       — a Protocol that every metric module must satisfy.
                     Structural subtyping: no inheritance needed, just
                     implement compute() with the correct signature.

Adding a new metric (e.g. delta-presence):
    1. Create  analytics/risk/metrics/delta_presence.py
    2. Implement a class that satisfies the Metric Protocol
    3. Register it in analytics/risk/__init__.py under METRICS
    → report.py and visual.py adapt automatically.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class RiskResult:
    """
    Standardised output produced by every metric.

    report.py and visual.py consume only this type — they have no
    knowledge of k-anonymity, l-diversity, or any other specific model.

    Attributes:
        name:            Human-readable name of the metric
                         (e.g. "k-Anonymity").
        passed:          True if the dataset satisfies the metric's
                         threshold; False otherwise.
        summary:         Top-level scalar metrics for the summary section
                         of the report (e.g. {"k_min": 3, "at_risk": 12}).
        details:         Per-equivalence-class or per-record breakdown,
                         used for detailed tables in the report.
        recommendations: Ordered list of actionable recommendations
                         derived from the results.
        charts:          List of SVG strings generated by visual.py.
                         Each string is a self-contained <svg>…</svg> block
                         ready to be embedded inline in the HTML report.
        threshold:       The threshold value used for the pass/fail verdict
                         (e.g. k=2, l=2, t=0.2). Stored for traceability.
        metadata:        Arbitrary key-value pairs for future extension
                         (e.g. algorithm variant, computation time).
    """

    name:            str
    passed:          bool
    summary:         Dict[str, Any]
    details:         List[Dict[str, Any]]
    recommendations: List[str]
    charts:          List[str]          = field(default_factory=list)
    threshold:       Any                = None
    metadata:        Dict[str, Any]     = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Metric Protocol
# ---------------------------------------------------------------------------

@runtime_checkable
class Metric(Protocol):
    """
    Protocol that every Risk metric module must satisfy.

    Only one method is required: compute(). It receives the anonymised
    records and keyword arguments specific to the metric (quasi-
    identifiers, sensitive attribute, thresholds, etc.) and returns a
    fully populated RiskResult.

    The name class attribute is used by the registry and the report
    generator as a stable identifier.

    Example implementation skeleton:

        class MyMetric:
            name = "My Metric"

            def compute(
                self,
                records: List[Dict[str, Any]],
                **kwargs,
            ) -> RiskResult:
                ...
                return RiskResult(
                    name=self.name,
                    passed=...,
                    summary={...},
                    details=[...],
                    recommendations=[...],
                )
    """

    #: Stable display name used in reports and registry keys.
    name: str

    def compute(
        self,
        records: List[Dict[str, Any]],
        **kwargs: Any,
    ) -> RiskResult:
        """
        Run the metric against a list of records.

        Args:
            records:  The anonymised dataset as a list of dicts.
            **kwargs: Metric-specific parameters, e.g.:
                      - quasi_identifiers: List[str]
                      - sensitive_attr:    str
                      - k_threshold:       int
                      - l_threshold:       int
                      - t_threshold:       float

        Returns:
            A fully populated RiskResult.
        """
        ...

    def chart(self, summary: Dict[str, Any]) -> List[str]:
        """
        Generate SVG charts for the metric's results.

        Each metric is responsible for its own visualisations.
        visual.py provides SVG primitives; the metric assembles them.

        Args:
            summary: The summary dict from a computed RiskResult.

        Returns:
            A list of self-contained SVG strings to embed in the report.
            May return an empty list if no chart is applicable.
        """
        ...