"""
maskme.utility.base
~~~~~~~~~~~~~~~~~~~~
Formal contracts for the data utility layer.

Two building blocks:

    UtilityResult — standardised dataclass that every utility metric returns.
                    report.py works exclusively with this type, making it
                    agnostic to any specific metric.

    Metric        — Protocol that every metric module must satisfy.
                    Structural subtyping: implement compute() and chart()
                    with the correct signatures — no inheritance needed.

Adding a new metric (e.g. ML-utility):
    1. Create  analytics/utility/metrics/ml_utility.py
    2. Implement a class that satisfies the Metric Protocol
    3. Register it in analytics/utility/__init__.py under METRICS
    → run(), report.py adapt automatically.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class UtilityResult:
    """
    Standardised output produced by every utility metric.

    report.py consumes only this type — it has no knowledge of
    field_retention, statistical_fidelity, or any specific metric.

    Attributes:
        name:            Human-readable name of the metric
                         (e.g. "Field Retention").
        score:           Global utility score in [0, 1].
                         1.0 = perfect utility (no degradation),
                         0.0 = complete utility loss.
        summary:         Top-level scalar metrics for the summary section
                         (e.g. {"retention_rate": 0.82, "dropped_fields": 2}).
        details:         Per-field breakdown used for detailed tables.
        recommendations: Ordered list of actionable recommendations.
        charts:          List of SVG strings generated by the metric's
                         chart() method. Each is a self-contained
                         <svg>…</svg> block for inline HTML embedding.
        threshold:       Optional minimum acceptable score. If provided,
                         passed = score >= threshold.
        passed:          True if score meets the threshold (or if no
                         threshold is set). Defaults to True.
        metadata:        Arbitrary key-value pairs for extension
                         (e.g. metric variant, field counts).
    """

    name:            str
    score:           float                  # global utility score [0, 1]
    summary:         Dict[str, Any]
    details:         List[Dict[str, Any]]
    recommendations: List[str]
    charts:          List[str]              = field(default_factory=list)
    threshold:       float                  = 0.0
    passed:          bool                   = True
    metadata:        Dict[str, Any]         = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Metric Protocol
# ---------------------------------------------------------------------------

@runtime_checkable
class Metric(Protocol):
    """
    Protocol that every utility metric module must satisfy.

    Two methods are required:
        compute() — runs the metric and returns a UtilityResult.
        chart()   — generates SVG charts from a summary dict.

    Each metric is self-contained: it owns both its computation and its
    visualisation. utility/visual.py provides SVG primitives; the metric
    assembles them.

    Example implementation skeleton:

        class MyMetric:
            name = "My Metric"

            def compute(
                self,
                original: List[Dict[str, Any]],
                anonymised: List[Dict[str, Any]],
                **kwargs,
            ) -> UtilityResult:
                ...
                return UtilityResult(
                    name=self.name,
                    score=...,
                    summary={...},
                    details=[...],
                    recommendations=[...],
                )

            def chart(self, summary: Dict[str, Any]) -> List[str]:
                ...
                return [svg_string]
    """

    #: Stable display name used in reports and registry keys.
    name: str

    def compute(
        self,
        original: List[Dict[str, Any]],
        anonymised: List[Dict[str, Any]],
        **kwargs: Any,
    ) -> UtilityResult:
        """
        Run the metric against original and anonymised datasets.

        Args:
            original:   The original dataset before anonymization.
            anonymised: The anonymised dataset produced by MaskMe.
            **kwargs:   Metric-specific parameters, e.g.:
                        - numerical_fields:   List[str]
                        - categorical_fields: List[str]
                        - threshold:          float

        Returns:
            A fully populated UtilityResult.
        """
        ...

    def chart(self, summary: Dict[str, Any]) -> List[str]:
        """
        Generate SVG charts from a computed summary dict.

        Args:
            summary: The summary dict from a UtilityResult.

        Returns:
            A list of self-contained SVG strings. May be empty.
        """
        ...